### ISSUE TITLE
Unable to Start Server with Local Secret

### ISSUE THREAD

**Issue by DaveL17** [mlamoure/indigo-auto-lights#3]
This could be a bug or it could be PEBKAC...

```
   Auto Lights Warning             Cannot start web server because Indigo API connection failed.
```
- I'm able to spool up the configuration server using the reflector URL and an API key; however, I'm not able to spool it up using a local secret against `localhost`. 
- I've tried several variations of plugin config parameters, but no joy. 
  - `localhost`, `localhost:8176`, `https://localhost`, `https://localhost:8176` and same with loopback `127.0.0.1`.
- I can confirm that the secrets file and secret is valid as I can hammer the API server with direct calls in Safari.

Can you confirm it's working for you and, if so, provide a specific example of how you want the plugin params set for only local control?

**Comment by DaveL17** [comment]
I don't know if you've had a chance to look at this yet, but I've found what the issue is. In its current form, the plugin only supports local secrets with the Indigo server set to disable `https://`. Then the Auto Lights server will spool up with the following settings:

Reflector URL: `http://localhost:8176`
API Key: `my_local_secret` (no quotes)

With these settings, I was able to successfully load the plugin web configuration tool. I would respectfully request that `https` be supported.

**Comment by mlamoure** [comment]
Thanks for investigating.  It was next on my list.  I do not explicitly require http for the local secrets.  The plugin does not distinguish a difference between reflector and local.  I'm guessing that local with https the certificate is not valid.  I'll need to ignore certificate errors when local.  Is that an acceptable solution?

**Comment by DaveL17** [comment]
I honestly don't know what Matt & Jay do as far as using/approving the cert for local secrets, but `https` definitely works with a local secret when hitting a URL like:

`https://localhost:8176/v2/api/indigo.devices?api-key=my_local_secret`

**Comment by mlamoure** [comment]
Appreciate the compliment.  One glaring miss on my implementation was that I'm not using the HTTP Handler that Matt and Jay built into the latest Indigo API.  This is why the plugin requires a API key to interact, otherwise this could be avoided.  I was not able to figure out how to use the template rendering engine I'm using -- WTForms.  This was important to me as it drove a schema-based form rather than a custom UI.

**Comment by DaveL17** [comment]
I may not be of much help with that because I've affirmatively trusted the self-signed certificate for the various endpoints. But before that, I didn't get a cert error --  I got a warning that the cert was untrusted.

**Comment by mlamoure** [comment]
No prob.  I'm pretty sure that's the issue based on my quick testing.  I've added a Disable SSL Verify flag to the PluginConfig, it'll be in the next version.

**Comment by DaveL17** [comment]
Oh, yeah.  If you're using something like `requests` to move stuff around, then definitely need to set verify to false. We've been slow marching over to `httpx`--which also has the flag--because it allows for the verify to "fail" silently (among other reasons).

I just realized that I never answered your client question. I was using Safari to test the URL with a local secret.

**Comment by mlamoure** [comment]
Try out 2025.0.2 that I just pushed.  See if that resolves for you.

**Comment by DaveL17** [comment]
Still not working for me with `https` enabled on the Indigo server.

**Comment by DaveL17** [comment]
Sure!

```
   Starting plugin "Auto Lights 2025.0.2" (pid 25973)
   Processing requirements for plugin "Auto Lights 2025.0.2"
   Requirements for "Auto Lights 2025.0.2" previously processed, continuing startup
   Started plugin "Auto Lights 2025.0.2"
   Auto Lights Debug               startup called
   Auto Lights Warning             Cannot start web server because Indigo API connection failed.
   Auto Lights Debug               [caller: load_config:200][func: from_config_dict] from_config_dict called
   Auto Lights Debug               [caller: load_config:200][func: from_config_dict] from_config_dict finished
   Auto Lights Debug               refresh_all_indigo_devices: starting refresh of all Indigo devices
```

Do you have `https://` enabled when you start the Indigo server?

**Comment by mlamoure** [comment]
This is my server startup screen, does this match yours?  

<img width="595" alt="Image" src="https://github.com/user-attachments/assets/4c42a3d7-2752-457a-920d-800451a1ecde" />

**Comment by DaveL17** [comment]
Essentially, yes. The only potentially noteworthy difference is that my reflector is activated and yours is awaiting activation.

**Comment by DaveL17** [comment]
Apologies -- somehow I unchecked the SSL validation checkbox. With it checked, it works with the local secret. 

2025.0.2 fixes it.

#goose_chase #pebkac

**Comment by mlamoure** [comment]
No worries.  I'll push another update with some improvements to the plugin config UI.  Glad it's working for you.

**Comment by mlamoure** [comment]
BTW -- I found a bug where closedPrefsConfigUi was not applying the changes correctly.  That may have been contributing to the confusion here.  Apologies for that.  Being fixed in next version.
